### ISSUE TITLE
The `child`  should be last widget on constructor invocations.

### ISSUE THREAD

**Issue by yeasin50** [SimformSolutionsPvtLtd/flutter_showcaseview#360]
**Describe the bug**
I am using `sdk: '>=2.19.3 <3.0.0'` with `flutter_lints: ^2.0.0`. While creating an instance of `Showcase` it uses the second position for child which cause the lint warning. 

```dart
Showcase(
  key: _fkey,
  child: child,
  description: description,
)
```

**To Reproduce**
1. create project on recent flutter version.
2.  while using auto-suggestion, press enter
3. this sort the named argument based on constructor parameters position.

**Expected behavior**

```dart
Showcase(
  key: _fkey,
  description: description,
  child: child,
)
```
**Screenshots**
 
![image](https://user-images.githubusercontent.com/46500228/225988996-8e9e82d9-30a0-453c-a311-fa621e14ae75.png)

**Device**
 - VS code Windows 10

<details><summary>pubspec.yaml</summary>

```
name: example2
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  showcaseview:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```
</details>
