### ISSUE TITLE
Showcaseview alignment issue in web

### ISSUE THREAD

**Issue by irshad-hz** [SimformSolutionsPvtLtd/flutter_showcaseview#418]
Using showcase view in mobile it is working fine but in web it is not aligning prpoerly it is mismatching the widget.

**Comment by vatsaltanna-simformsolutions** [comment]
Please share all the details mentioned in issue template. which will help us reproduce the issue and we can easily fix it.

**Comment by irshad-hz** [comment]
![Screenshot 2024-04-17 at 3 22 01 PM](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/81296031/f67e87f5-a795-46e5-a6bd-053e433e2f4c)

i have wraped the showcase on the Add button but the overlay is coming below the button

**Comment by aditya-css** [comment]
Hello @irshad-hz, Thank you for raising this issue. Can you please try using the code from master branch and then see if you still face this issue?
You can do that by writing this in your pubspec.yaml:
```
  showcaseview:
    git:
      url: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview.git
      ref: master
```
